datalore-env-format-version: "0.2"
datalore-package-manager: "pip"
datalore-base-env: "minimal"
dependencies:
- pip:
  - librosa==0.10.0.post2
  - PyYAML==6.0
  - PyYAML==6.0
  - torch==2.0.1
  - torch-fidelity==0.3.0
  - scipy
  - importlib_resources==5.12.0
  - torchaudio>=0.13.0
  - torchvision>=0.14.0
  - tqdm
  - omegaconf
  - einops
  - numpy<=1.23.5
  - soundfile
  - pandas
  - torchlibrosa == 0.1.0
  - transformers==4.18.0
  - ftfy
  - pytorch-lightning==1.7.0
  - torchmetrics==0.11.1
  - sentence-transformers
  - git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
